### PR TITLE
web docs redirects

### LINKED ISSUE #691: Broken Docs Pages
https://www.eidolonai.com/docs/howto/customize_builtins
https://www.eidolonai.com/docs/components/simple_agent#defining-actions

### PR DESCRIPTION
**Pull request by flynntsang**
should fix #691

### CODE REVIEW

**Review by LukeLalor — CHANGES_REQUESTED** [review]
should we find those old links and fix them instead?

**Comment by flynntsang** [comment]
> should we find those old links and fix them instead?

We should, but it's very common to have long redirects. There might be links in emails and who-knows-what that we don't have control over.

**Comment by LukeLalor** [comment]
> > should we find those old links and fix them instead?
> 
> We should, but it's very common to have long redirects. There might be links in emails and who-knows-what that we don't have control over.

adding the redirects is fine, but we should also fix the links in 
what_is_agent.mdx
README.md

**Comment by flynntsang** [comment]
@LukeLalor Please give the files another look-over.

@abhi-vachani I was in the quickstart.md file and made the changes from hello_world to hello-world where appropriate.

**Review by LukeLalor — APPROVED** [review]

**Pull request merged**
