### PR TITLE
OpenAI request `NotFoundError` response adds additional context to indicate potential lack of funds

### PR DESCRIPTION
**Pull request by coryfoo**
When an OpenAI token is used that either does not have billing enabled or does not have enough credits to call the default model, their API will raise an exceptionof type `NotFoundError`. 

When this happens, we will catch the errors of this type and modify the message to include additional context that indicates that the issue may be related to insufficient credits. We will then re-raise an `APUException`.

Fixes issue #709

### CODE REVIEW

**Comment by coryfoo** [comment]
When looking into this issue, I also considered a potentially more robust implementation that checked for the available OpenAI models at server start time and halted (or at least logged pretty aggressively). I ultimately decided against that "belt and suspenders" approach as this is a really a transitory issue that could easily be remedied without a server restart. That, and as I am new to this project, I was not sure how welcome a change would be that veers outside the scope declared within the issue.

**Comment by LukeLalor** [comment]
thanks @coryfoo! This will already be a much better error.

Could you add an api level test to verify the response? `sdk/tests/test_sql_agent.py` is a pretty tight example for how to define a test module that starts the server with a custom agent definition. Obviously you would need to use the SimpleAgent instead of the SqlAgent, but you get the idea.

Another potential addition is is to make a request request to https://platform.openai.com/docs/api-reference/models/list in the catch block so that we can disambiguate bad model vs unfunded account. We would need to guard against errors here, but it could allow us to be very helpful in most cases.

**Comment by coryfoo** [comment]
> Could you add an api level test to verify the response? `sdk/tests/test_sql_agent.py` is a pretty tight example for how to define a test module that starts the server with a custom agent definition. Obviously you would need to use the SimpleAgent instead of the SqlAgent, but you get the idea.

I'd be happy to do that! Is there an existing test file that makes sense to dump the test into, or should I create a new one?

**Comment by LukeLalor** [comment]
> > Could you add an api level test to verify the response? `sdk/tests/test_sql_agent.py` is a pretty tight example for how to define a test module that starts the server with a custom agent definition. Obviously you would need to use the SimpleAgent instead of the SqlAgent, but you get the idea.
> 
> I'd be happy to do that! Is there an existing test file that makes sense to dump the test into, or should I create a new one?



> > Could you add an api level test to verify the response? `sdk/tests/test_sql_agent.py` is a pretty tight example for how to define a test module that starts the server with a custom agent definition. Obviously you would need to use the SimpleAgent instead of the SqlAgent, but you get the idea.
> 
> I'd be happy to do that! Is there an existing test file that makes sense to dump the test into, or should I create a new one?



> > Could you add an api level test to verify the response? `sdk/tests/test_sql_agent.py` is a pretty tight example for how to define a test module that starts the server with a custom agent definition. Obviously you would need to use the SimpleAgent instead of the SqlAgent, but you get the idea.
> 
> I'd be happy to do that! Is there an existing test file that makes sense to dump the test into, or should I create a new one?



> > Could you add an api level test to verify the response? `sdk/tests/test_sql_agent.py` is a pretty tight example for how to define a test module that starts the server with a custom agent definition. Obviously you would need to use the SimpleAgent instead of the SqlAgent, but you get the idea.
> 
> I'd be happy to do that! Is there an existing test file that makes sense to dump the test into, or should I create a new one?

You can create a new test file. Most of our other tests are parameterized by llm provider, and we just want it for openai.

**Comment by coryfoo** [comment]
@LukeLalor I made a new test file, per your request. I didn't exactly copy the `test_sql_agent.py` pattern, however, as my feeling was that the goal was to assert that the error message was appropriate when the OpenAI client threw a `NotFoundError`. Therefore, I mocked out a new subclass of `OpenAIConnectionHandler` so that we could make it raise the error. I felt that going the route of starting a server and configuring an agent was a less direct path of accomplishing this goal.

**Comment by LukeLalor** [comment]
sounds good. Thanks for that @coryfoo 

failing lock file test is due to external contributors bug. I filed it at https://github.com/eidolon-ai/eidolon/issues/794 and will merge bypass the rule.

**Pull request merged**
